[package]
authors = ["Tom Prince <tom.prince@twistedmatrix.com>"]
name = "clock-chime"
version = "0.1.2"

[dependencies]
chrono = "0.2.25"
clap = "2.20.0"
error-chain = "0.8.1"
lazy_static = "0.2.2"
rodio = "0.4.2"
