#!/usr/bin/python
from __future__ import print_function

from datetime import datetime, timedelta
from pycanberra import Canberra

now = datetime.now()
canberra = Canberra()

hour = timedelta(seconds=3600)

if now.minute < 7.5:
    canberra.easy_play_sync(now.strftime("grandfather-clock-chime-%I"))
elif 7.5 < now.minute < 22.5:
    canberra.easy_play_sync("grandfather-clock-chime-one-quarter")
elif 22.5 < now.minute < 37.5:
    canberra.easy_play_sync("grandfather-clock-chime-one-half")
elif 37.5 < now.minute < 52.5:
    canberra.easy_play_sync("grandfather-clock-chime-three-quarter")
elif now.minute > 52.5:
    canberra.easy_play_sync((now+hour).strftime("grandfather-clock-chime-%I"))
